# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kwin

# >> macros
# << macros

Summary:    KDE Window manager
Version:    5.0.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kwin.yaml
Source101:  kwin-rpmlintrc
Requires:   kf5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5UiTools)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xcursor)
BuildRequires:  pkgconfig(sm)
BuildRequires:  pkgconfig(ice)
BuildRequires:  pkgconfig(xcb-keysyms)
BuildRequires:  pkgconfig(xcb-image)
BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:  pkgconfig(epoxy)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kconfig-devel
BuildRequires:  kconfigwidgets-devel
BuildRequires:  kcoreaddons-devel
BuildRequires:  kcrash-devel
BuildRequires:  kglobalaccel-devel
BuildRequires:  ki18n-devel
BuildRequires:  kinit-devel
BuildRequires:  knotifications-devel
BuildRequires:  kservice-devel
BuildRequires:  plasma-devel
BuildRequires:  kwidgetsaddons-devel
BuildRequires:  kwindowsystem-devel
BuildRequires:  kdoctools-devel
BuildRequires:  kcmutils-devel
BuildRequires:  knewstuff-devel
BuildRequires:  kactivities-libs-devel
BuildRequires:  kdoctools-devel
BuildRequires:  libGL-devel
BuildRequires:  libEGL-devel

%description
KDE Window manager


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kconfig-devel
Requires:   kwidgetsaddons-devel

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%package doc
Summary:    User manual for %{name} %{name}
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
User manual for %{name}.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COMPLIANCE COPYING COPYING.DOC HACKING README
%{_kf5_bindir}/kwin_x11
%{_kf5_sharedir}/kwin
%{_kf5_libdir}/libkdeinit5_kwin.so
%{_kf5_libdir}/libkdeinit5_kwin_rules_dialog.so
%{_kf5_libdir}/libkdecorations.so.*
%{_kf5_libdir}/libkwinxrenderutils.so.*
%{_kf5_libdir}/libkwineffects.so.*
%ifarch %{arm}
%{_kf5_libdir}/libkwinglesutils.so.*
%endif
%ifarch %{ix86} x86_64
%{_kf5_libdir}/libkwinglutils.so.*
%endif
%{_kf5_libdir}/libkwin4_effect_builtins.so.*
%{_kf5_plugindir}/*
%{_kf5_qmldir}/*
%{_kf5_libdir}/kconf_update_bin/kwin5_update_default_rules
%{_kf5_libdir}/libexec/kwin_killer_helper
%{_kf5_libdir}/libexec/kwin_rules_dialog
%{_kf5_sharedir}/kwincompositing
%{_kf5_servicesdir}/*
%{_kf5_servicetypesdir}/*
%{_kf5_sharedir}/knotifications5/kwin.notifyrc
%{_kf5_sharedir}/config.kcfg/kwin.kcfg
%{_kf5_sharedir}/icons/hicolor/*
%{_kf5_configdir}/*.knsrc
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kf5_cmakedir}/KWinDBusInterface
%{_kf5_cmakedir}/KDecorations
%{_kf5_dbusinterfacesdir}/*.xml
%{_kf5_libdir}/libkdecorations.so
%{_kf5_libdir}/libkwinxrenderutils.so
%{_kf5_libdir}/libkwineffects.so
%ifarch %{arm}
%{_kf5_libdir}/libkwinglesutils.so
%endif
%ifarch %{ix86} x86_64
%{_kf5_libdir}/libkwinglutils.so
%endif
%{_kf5_libdir}/libkwin4_effect_builtins.so
%{_includedir}/*
# >> files devel
# << files devel

%files doc
%defattr(-,root,root,-)
%doc COMPLIANCE COPYING COPYING.DOC HACKING README
%{_kf5_htmldir}/en/kcontrol/*
# >> files doc
# << files doc
